apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dep
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: v1
        image: princeriyas/bootdocker:v1
        ports:
        - containerPort: 81